// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6CFFGQ6eUCKkJuTa31H7MqBtlRe9aNRY',
    appId: '1:1058102347853:web:871bcb8093fa98aeb7f404',
    messagingSenderId: '1058102347853',
    projectId: 'ireadv2-16c79',
    authDomain: 'ireadv2-16c79.firebaseapp.com',
    storageBucket: 'ireadv2-16c79.firebasestorage.app',
    measurementId: 'G-TXJQ6FPQTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQaV5vPRpSJh1LAYANzoUCBge7Xdw4eMc',
    appId: '1:1058102347853:android:2592e4467d20cdafb7f404',
    messagingSenderId: '1058102347853',
    projectId: 'ireadv2-16c79',
    storageBucket: 'ireadv2-16c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwsxBsZmVtWLUyecQ5GvrNgj1V4ISQ64E',
    appId: '1:1058102347853:ios:0c6619005dbd437fb7f404',
    messagingSenderId: '1058102347853',
    projectId: 'ireadv2-16c79',
    storageBucket: 'ireadv2-16c79.firebasestorage.app',
    iosBundleId: 'com.iread.iread',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwsxBsZmVtWLUyecQ5GvrNgj1V4ISQ64E',
    appId: '1:1058102347853:ios:0c6619005dbd437fb7f404',
    messagingSenderId: '1058102347853',
    projectId: 'ireadv2-16c79',
    storageBucket: 'ireadv2-16c79.firebasestorage.app',
    iosBundleId: 'com.iread.iread',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6CFFGQ6eUCKkJuTa31H7MqBtlRe9aNRY',
    appId: '1:1058102347853:web:cd31cf9bb9cd9affb7f404',
    messagingSenderId: '1058102347853',
    projectId: 'ireadv2-16c79',
    authDomain: 'ireadv2-16c79.firebaseapp.com',
    storageBucket: 'ireadv2-16c79.firebasestorage.app',
    measurementId: 'G-3DX0HT0R4Z',
  );
}
